data:
  path: data/
  dataset: darcy
  batch_size: 64
  num_workers: 4
  num_samples: 10000
  shape_setting: [[32, 1]] # first element resolution, second element percentage
                                        # resolutions sampled from multinomial distribution
  targets:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
  mono: True
  upper: null
  lower: null
model:
  name: CAF
  name_sr: null
  loss_unit: null
  is_gan: False # if True, return tuple loss in forward pass, 
                # first element being generator loss, second element discriminator loss,
                # wrap both generator and discriminator in a single class,
                # set generator training frequency internally,
                # train either generator or discriminator in a single forward pass,
                # loss for part that's not trained needs to be None
  details:
    NAF:
      shape: [1, 1, 28, 28]
    CAF:
      shape: [1, 1, 16, 16]
      depth_1: 8
      depth_2: 8
      depth_3: 16
      modes: 16
      fourier: True
      normalize: True
    CAFMod:
      shape: [1, 1, 16, 16]
      depth_1: 4
      depth_2: 4
      depth_3: 8
      modes: 16
      fourier: True
      normalize: False
    CAFFNO:
      shape: [1, 1, 16, 16]
      ar_depth: 8
      ar_width: 32
      depth_1: 4
      depth_2: 4
      depth_3: 8
      modes: 16
      fourier: True
      normalize: False
    CFFNO:
      shape: [1, 1, 28, 28]
      depth: 8
      width: 64
      modes: 12
    CAFGRF:
      shape: [1, 1, 16, 16]
      depth_1: 4
      depth_2: 4
      depth_3: 8
      modes: 16
      ar_depth: 8
      num_res: 2
      ar_hid: 32
    MultilevelDiff:
      prior_modes_1: 28
      prior_modes_2: 14
      prior_scale: 1
      width: 64
    Gano:
      d_co_domain: 20
      modes_schedule: [12, 8, 4, 2]
      npad: 2
      n_critic: 5
      default_res: 28
      lambda_grad: 10
      alpha: 1.5
      tau: 1
    ResSNO:
      n_layers: 64
      dim_hidden: 128
      depth: 3
      k_max: 7
      n_fourier_coeffs: null
      coeff: 0.98
      n_ldj_iter: null
      n_exact_terms: 2
      n_fixed_iter: 50
      use_unbiased: False
      n_spectral_iter: 20
      type: grf
      ls: 0.1
      var: 1
      eps: 0.001
    WaveletFlow:
      num_scales: 2
      max_res: 64
      step_settings: [16, 16, 16] # depths of flow, the last one is for unconditional flow
      conv_settings: [128, 128, 128] # width of convolution channels
      base_split: True
    PixelTransformer:
      ndp: 2
      ndv: 1
      nde: 128
      nhead: 4
      num_bins: 256
      num_encoder_layers: 10
      num_decoder_layers: 10
      mode: "fourier"
      init_factor: 2
      context_num: 110
      sample_mean: False
    PixelTransformerSR:
      ndp: 2
      ndv: 1
      nde: 128
      nhead: 4
      num_bins: 256
      num_encoder_layers: 8
      num_decoder_layers: 12
      mode: "fourier"
      init_factor: 2
      context_num: 64
      sample_mean: False
    PixelTransformerAug:
      ndp: 2
      ndv: 1
      nde: 128
      nhead: 4
      num_encoder_layers: 10
      num_decoder_layers: 10
      mode: "fourier"
      init_factor: 2
      context_num: 64
      sample_mean: False
    PixelVAE:
      ndp: 2
      ndv: 1
      nde: 64
      nhead: 4
      num_encoder_layers: 10
      num_decoder_layers: 10
      mode: "fourier"
      init_factor: 2
      context_num: 64
      sample_mean: False
    PixelFourierVAE:
      ndp: 2
      ndv: 2
      nde: 128
      nhead: 4
      num_encoder_layers: 10
      num_decoder_layers: 10
      mode: "fourier"
      init_factor: 2
      context_num: 64
      sample_mean: False
    PixelFourier:
      ndp: 2
      ndv: 2
      nde: 128
      nhead: 4
      num_encoder_layers: 10
      num_decoder_layers: 10
      mode: "fourier"
      init_factor: 2
      context_num: 8
      sample_mean: False
    PixelTransformerFourierCoupling:
      ndp: 2
      ndv: 2
      nde: 128
      nhead: 8
      num_flow_layers: 32
      num_encoder_layers: 10
      num_decoder_layers: 10
      mode: "fourier"
      init_factor: 2
      context_num: 16
      sample_mean: False
    StochFlow:
      num_coupling_layers: 8
      num_steps: 10
    parapflow:
      in_d: 1
      num_head: 4
      depth_1: 4
      depth_2: 4
      depth_3: 8
    PatchTransformer:
      patch_size: 4
      dim: 512
      depth: 8
      heads: 8
      channels: 1
      beta: 0.01
    PatchVAE:
      patch_size: 16
      n_hid: 256
    PixelPatchTransformerFlow:
      ndp: 2
      ndv: 1
      nde: 128
      nhead: 8
      num_flow_layers: 32
      num_encoder_layers: 10
      num_decoder_layers: 10
      mode: "fourier"
      init_factor: 2
      context_num: 16
      patch_res: 4
      num_rand_samples: 16
    UnetFlow:
      base_res: 16
      context_num: 16
    RealNVP:
      depth_1: 6
      depth_2: 6
      depth_3: 12
train:
  epochs: 51
  lr: 0.00001
  lr_d: 0.00001 # discriminator learning rate, ignore if model is not GAN based
  save_freq: 1
  test_freq: 1
  save_path: tmp/runs/ckpt/ # path to save the trained model's checkpoint
  test_path: tmp/runs/test/ # path to save the test results
  test_lowest_resolution: null
  load_path: tmp/runs/ckpt/CAF_darcy_32_epoch_7.pth # null to train a new model
  load_path_sr: null
  save_name: PPTF_darcy_20_24_28_32_48_64
  test_resolutions: [20, 28, 32, 48]
MMD_test:
  resolutions: [20, 24, 28, 32, 48, 64]
  batch_size: 1
  num_batch: 100
  pickle_save_dir: test/mmd_test/