data:
  path: data/
  dataset: mnist
  batch_size: 64
  num_workers: 4
  num_samples: 10000
  varying_shape: True
  shape_setting: [[28, 0.9], [64, 0.1]]
  targets:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
  mono: True
model:
  name: CouplingFlowAR
  loss_unit: bpd
  is_gan: False # if True, return tuple loss in forward pass, 
                # first element being generator loss, second element discriminator loss,
                # wrap both generator and discriminator in a single class,
                # set generator training frequency internally,
                # train either generator or discriminator in a single forward pass,
                # loss for part that's not trained needs to be None
  details:
    CouplingFlowAR:
      shape: [1, 1, 16, 16]
      depth_1: 4
      depth_2: 4
      depth_3: 8
      modes: 16
      fourier: True
      normalize: False
    CouplingFlowARMod:
      shape: [1, 1, 16, 16]
      depth_1: 4
      depth_2: 4
      depth_3: 8
      modes: 16
      fourier: True
      normalize: False
    MultilevelDiff:
      prior_modes_1: 28
      prior_modes_2: 14
      prior_scale: 1
      width: 64
    Gano:
      d_co_domain: 20 
      modes_schedule: [12, 8, 4, 2]
      npad: 2
      n_critic: 5
      default_res: 28
      lambda_grad: 10
      alpha: 1.5
      tau: 1
    ResSNO:
      n_layers: 64
      dim_hidden: 512
      depth: 3
      k_max: 7
      n_fourier_coeffs: null
      coeff: 0.98
      n_ldj_iter: null
      n_exact_terms: 2
      n_fixed_iter: 50
      use_unbiased: False
      n_spectral_iter: 20
      type: standard
      ls: 0.1
      vars: 1
      eps: 0.001
train:
  epochs: 30
  lr: 0.00001
  lr_d: 0.00001
  save_freq: 5
  test_freq: 5
  save_path: tmp/runs/ckpt/
  test_path: tmp/runs/test/
  test_lowest_resolution: 28
  load_path: null
  save_name: CouplingFlowAR_10
MMD_test:
  resolutions: [28, 32]
  test_model: CouplingFlowAR
  model_pth: tmp/runs/saved_ckpt/coupling_ar_epoch_19.pth
  batch_size: 500